---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nftgw
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
     - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - get
    - list
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nftgw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nftgw
subjects:
- kind: ServiceAccount
  name: nftgw
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nftgw
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nftgw
  namespace: kube-system
  labels:
    tier: node
    app: nftgw
    k8s-app: nftgw
spec:
  selector:
    matchLabels:
      app: nftgw
  template:
    metadata:
      labels:
        tier: node
        app: nftgw
        k8s-app: nftgw
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: nftgw
      containers:
      - name: nftgw
        image: aojea/nftgw:v0.0.1
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_RAW", "NET_ADMIN"]
